### ISSUE TITLE
System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).

### ISSUE THREAD

**Issue by martmas** [tsarjak/WallpapersFromReddit#31]
Hello, 

got following error. Downloader used work for me fine in past. My laic guess this is due to some changes Reddit made recently.

```
[ERROR]: An error occurred while downloading images for user "someusername". Please try again later. If this error occurs repeatedly, file a bug.
System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at DownloadRedditImages.Program.Get(String author, Int32 createdAfter) in E:\Software\My Software\DownloadRedditImages\DownloadRedditImages\Program.cs:line 207
   at DownloadRedditImages.Program.Download(String author) in E:\Software\My Software\DownloadRedditImages\DownloadRedditImages\Program.cs:line 70
   at DownloadRedditImages.Program.Main(String[] args) in E:\Software\My Software\DownloadRedditImages\DownloadRedditImages\Program.cs:line 49
```

ps. this is my first post on github, so I hope it belongs here. If not, then sorry.

**Comment by tsarjak** [comment]
Hi, yes this definitely belongs here. Haven't been maintaining the code for a while now.

Your guess seems correct, either Reddit made some changes, or you exhausted rate limits on accessing reddit. Will check soon
